[package]
name = "measures"
version = "0.1.0"
edition = "2018"
description = "A unit-of-measure and electrical calculations library."
repository = "https://github.com/arnolddevos/measures.git"
license = "Apache-2.0"
readme = "README.md"
